# Schema for the configuration files of the frontend editing module.

frontend_editing.settings:
  type: config_object
  label: 'Frontend Editing settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Supported entity types'
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
          type: string
    sidebar_width:
      type: integer
      label: 'Sidebar width'
    full_width:
      type: integer
      label: 'Full width'
    ajax_content_update:
      type: boolean
      label: 'Ajax content update'
    exclude_fields:
      type: sequence
      label: 'Exclude fields'
      sequence:
        type: string
